### ISSUE TITLE
fatal error: dissect.h: No such file or directory

### ISSUE THREAD

**Issue by mlite** [Theldus/PBD#9]
I tried to build the latest code, and got this error.  I cannot find this file in this repo.

**Comment by mlite** [comment]
what is the minimum version of GCC that can build this code?  my gcc does not have this __builtin_clrsb

**Comment by Theldus** [comment]
Hi @mlite, dissect.h is part of libsparse, library that is included as a submodule in this repo... so please, clone this repository recursively, as instructed in the README.md:
`git clone --recursive https://github.com/Theldus/PBD.git`


> what is the minimum version of GCC that can build this code? my gcc does not have this __builtin_clrsb

I have tested on GCC 5.3+ and Clang 3.8+,
- What is your environment?
- Your process to build
- Output

PBD does not makes explicit use of `__builtin_clrsb`, so maybe this is used by libsparse, not PBD itself. Looking at [CompilerExplorer](https://gcc.godbolt.org/z/cnF5cj) looks like this builtin is supported at GCC 4.7.1+.

**Comment by mlite** [comment]
I need to make some modifications to build the code. But I did successfully build a statically linked PBD. I will do some testing with my build.

**Comment by mlite** [comment]
I use debian/i386 docker image to build it.

**Comment by mlite** [comment]
Need a quick advice:  how to change the line format from "[a.c6]"  to "file:/a.c::6"?
